export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
export const LOGOUT_USER = "LOGOUT_USER";

export const COCKTAILS_REQUEST = "COCKTAILS_REQUEST";
export const COCKTAILS_ERROR = "COCKTAILS_ERROR";
export const COCKTAILS_SUCCESS = "COCKTAILS_SUCCESS";
export const GET_COCKTAIL_SUCCESS = "GET_COCKTAIL_SUCCESS";