export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
export const LOGOUT_USER = "LOGOUT_USER";

export const GET_COCKTAILS_SUCCESS = "GET_COCKTAILS_SUCCESS";
export const CREATE_COCKTAIL_SUCCESS = "CREATE_COCKTAIL_SUCCESS";